### ISSUE TITLE
Module does not allow for the creation of custom tags on subnets

### ISSUE THREAD

**Issue by cterence** [padok-team/terraform-aws-network#29]
In order to use [subnet discovery with the ALB controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/deploy/subnet_discovery/), you should be able to tag subnets using the module.

**Comment by Nathan-LG** [comment]
This module is going to be merged in [terraform-aws-starter](https://github.com/padok-team/terraform-aws-starter/). 

As you can see [here](https://github.com/padok-team/terraform-aws-starter/pull/82/files#diff-cdf481ea1304a0120cdc751d6063523842c969bb7628b996633031343694ce25R106-R108), this migration will allow the use of tags on subnets.
